apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockchain-pvc
  labels:
    app: coubcore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard